### ISSUE TITLE
Any way to make this work for PS4 accounts?

### ISSUE THREAD

**Issue by MobileSam** [Andargor/edce-client#28]
I always end up getting an error that my credentials are invalid.
After sine digging, I see this error message:
>Please purchase/redeem elite dangerous to continue

**Comment by Andargor** [comment]
I honestly have no idea. I have no means of testing this since I play on PC, sorry. Maybe there's a different URL for the API? Seems it's supposedly in the same galaxy, so the market data and other info is valid.

Otherwise, I don't know if the PS4 update was recent, but for the PC the cAPI stopped working for a few days after launch.

**Comment by AnthorNet** [comment]
Console accounts are not available on the cAPI.
