### ISSUE TITLE
Generated filename for archive log - file with accent failed to be submit to EDDN

### ISSUE THREAD

**Issue by gbiobob** [Andargor/edce-client#6]
For commander with accent in cmdr name 
the file generated for the log (filename got the cmdr name => filename with an accent) failed to be submit on EDDN :
`EDCE: Error: EDDN postMarketData FAIL submit error.`

Converting filename with unicode colld be good to create filename without special character,
here a small exemple in py :

> import unicodedata
> ...
> path = u'log/*.xz' 
> ...
>   filenametmp = unicodedata.normalize('NFD', filename).encode('ascii', 'ignore')
>   pathSaveTmp = 'log/'+filenametmp.decode('ascii')+'.tmp.gz'
> ...

**Comment by gbiobob** [comment]
The issue #6 seem to be resolved,
Cmdr Vanité make a test there, he got the error : "Must be docked", prove is file get submitted and parsed (he leave the civilization to explore the galaxy). The file is parsed by EDDN to check market datas ? or you make check that before to send it ?

**Comment by Andargor** [comment]
It is important for the commander to be docked before sending to EDDN, because the data has the last system and last station. If you are not docked, the two might be unrelated. E.g. right now he's exploring, so his last system is where he is, but last station is the last time he docked.

I'll close for now and we'll see if this is causing issues for anyone, or for when your friend returns.
